### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-fd2ow#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by amitray007** [comment]
![image](https://user-images.githubusercontent.com/51674969/184480463-87a5607d-5d76-4a3d-9b4d-9be6557e78cf.png)

Updated codebase with hotfix for items without image using placeholder.
Re-tested manually and it's working as expected.
